## NOTE:  Do not edit this file.
##
if {[file exists work]} {
vdel -lib work -all
}
vlib work
vcom -explicit  -93 "complete_scheme.vhdl"
vcom -explicit  -93 "tb_complete_sine_map_scheme.vhd"
vsim -t 1ps -lib work tb_complete_sine_map_scheme
add wave sim:/tb_complete_sine_map_scheme/*

view wave
view structure
view signals
run 1000ms
quit -force